### PR TITLE
Remove duplicated margin property

### PR DESCRIPTION
**Pull request by evserykh**
Not really sure, though 🤔

### CODE REVIEW

**Comment by lspoor** [comment]
What's the need for this? 

`Margin` with a capital M is a fix for in Outlook.

**Comment by evserykh** [comment]
Sorry, didn't know

**Comment by lspoor** [comment]
No worries, here's some more info if you're interested.

https://www.emailonacid.com/blog/article/email-development/outlook.com-does-support-margins

**Comment by evserykh** [comment]
I'll see. Thanks a lot 👍

**Pull request closed without merging**
