### PR TITLE
Update sass-guide.md

### PR DESCRIPTION
**Pull request by pdenissen**
Before submitting a pull request, make sure it's targeting the right branch:
- For fixes to Ink 1.0, use `master`.
- For fixes to Foundation for Emails 2, use `v2.0`.

Happy coding! :)

Shouldn't "npm start" changed for "foundation watch". Npm start doesn't work. My terminal says that I should use foundation watch.

### CODE REVIEW

**Comment by tdhartwick** [comment]
`npm start` should work if you don't use the Foundation CLI. I think you'll only get that message if you set up a project with the Foundation CLI. Did you use the Foundation CLI?

**Comment by pdenissen** [comment]
Hi, that's correct. I use the Foundation CLI.
I guess you're right, but the docs aren't clear about this than. It starts with installing the Foundation CLI.
After these steps the next step is spinning up the server with NPM.
Thankfully my terminal said that I should use `foundation watch`.
Perhaps my edit isn't on the right place, but `foundation watch` should be mentioned.

**Comment by rafibomb** [comment]
I would suggest adding both but maybe in a non-confusing way.  `npm start` works wether or not you use the the CLI.

**Comment by khairyayman** [comment]
I would suggest adding both but maybe in a non-confusing way. http://emc-mee.com/movers-in-riyadh-company.html

**Pull request closed without merging**
