### PR TITLE
Ruby Gem

### PR DESCRIPTION
**Pull request by zokioki**
This PR provides a Ruby gem for the Foundation for Emails assets; its source can be found in the `/gem` directory. 

The gem's `vendor` folder is symlinked to the repo's top-level `scss` directory to ensure its assets stay up to date as changes are introduced to the project over time (props to @kball for this approach).

### CODE REVIEW

**Comment by kball** [comment]
The foundation-emails/foundation_emails split is a little weird (repo is foundation-emails, had to install foundation_emails)

**Comment by zokioki** [comment]
I decided to go with the standard convention of naming the gem with underscores if its module is named in a single level, multi-word fashion, based off of the [Rubygems guidelines](http://guides.rubygems.org/name-your-gem/).

There's definitely value in keeping the naming consistent across different packages - I can rename the gem if necessary.

**Comment by axelson** [comment]
Is there any more usage guidelines for the ruby gem? Does it work in the asset pipeline? Is there a better place to ask questions about it?

**Comment by rafibomb** [comment]
@axelson You can use it in the asset pipeline! Did you have a specific question about that can be added to the readme?

**Comment by axelson** [comment]
What extension needs to be used in the asset pipeline to convert inky templates into normal html?

**Comment by zokioki** [comment]
@axelson This gem packages the Foundation for Emails styles only, it does not contain the Inky parser itself.

We're working on such a gem, [**inky-rb**](https://rubygems.org/gems/inky-rb), which is a Ruby implementation of the Inky parser - this is what enables the conversion of Inky templates into normal HTML. For that, you would need to use the `.inky` file extension and make sure that your email layout includes a scss file that `@import`s the styles packaged in this gem.

The version of inky-rb currently published on Rubygems is a bit stale; I'll see if we can get a more recent build published for you.

**Comment by axelson** [comment]
Thanks @zokioki! Looking forward to being able to use the gem rather than the hacked up bash script we're currently using.

**Comment by zokioki** [comment]
@axelson As promised, an updated version of `inky-rb` (v0.0.3) was pushed to Rubygems. Here are some instructions on getting started with it:

Add the following gems to your Gemfile:

``` ruby
gem 'inky-rb', require: 'inky'
# Stylesheet inlining, letting you keep your email's markup and styling separated
gem 'premailer-rails'
```

Make sure that the stylesheet included in your email layout imports the Foundation for Emails styles:

``` scss
// your_emails_stylesheet.scss
@import "foundation-emails";
```

Rename your email templates to use the `.inky` file extension. Note that you'll still have access to your instance `@variable`s within `.inky` templates:

```
welcome.html      => welcome.html.inky
pw_reset.html.erb => pw_reset.html.inky
```

This should be all you need to get up and running. Hope it's helpful!

**Comment by axelson** [comment]
Sounds good! I'll test it out.

**Comment by zokioki** [comment]
The [inky-rb](https://github.com/zurb/inky-rb) repo has been opened, and v1.3.6.0 of the gem has been released - have at it y'all!

**Pull request merged**
