### PR TITLE
fix incorrect info about custom data and fix prototype link

### PR DESCRIPTION
**Pull request by zebapy**
Either the source files that have panini preconfigured need to be updated to add the `data: 'src/data'` path or the documentation should reflect the requirement. 

Also the prototyping link was dead. I'm not sure if this is the correct new link but I've added it for now.

**Edited** Remade PR as requested by @rafibomb in #492

### CODE REVIEW

**Comment by zebapy** [comment]
@rafibomb do you think the boilerplate/template should just include the `src/data` path to begin with?

**Comment by rafibomb** [comment]
Good question! Let's see what @kball thinks

**Comment by kball** [comment]
@zebapy I think it would make sense to have data in there by default with a sample/empty data file there as an example.

**Comment by rafibomb** [comment]
Thanks @kball 
@zebapy Is that something you can add to this PR? Would love to document this better in panini!

**Comment by zebapy** [comment]
@rafibomb I can add that, sure. That would be done in the [template project](https://github.com/zurb/foundation-emails-template), right?

**Comment by rafibomb** [comment]
Yes! The foundation-emails-template is what creates the project structure! Can you add it there too and the docs here can describe it.

**Comment by zebapy** [comment]
@rafibomb There's a PR open for custom data. I'll update this PR to remove the doc change and leave the link fix. https://github.com/zurb/foundation-emails-template/pull/20

**Comment by tdhartwick** [comment]
Thanks @zebapy! Merged in the updated Panini copy.

**Comment by Lulubbz** [comment]
Ohk

**Pull request merged**
