### PR TITLE
Use dart-sass and remove sass warnings

### PR DESCRIPTION
**Pull request by CPatchane**
[libsass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated), this PR replaces it by `dart-sass` instead.
Also fix sass deprecation warnings.

### CODE REVIEW

**Comment by czj** [comment]
Hello there ! Any way the maintainer could merge this PR so we can move on to `dart-sass` and remove those pesky warnings ? Thanks !

**Comment by sanderdlm** [comment]
Would love to see this merged. @joeworkman @DanielRuf if there's anything we can do to get this released let us know :slightly_smiling_face:

**Comment by czj** [comment]
Any way we can help, let us know !

**Comment by joeworkman** [comment]
Thanks guys. Email definitely needs some love. I hope to get to it soon.

**Comment by sadikoff** [comment]
Hello, I know everyone is pretty busy nowadays... But any updates here? Or maybe the community can bring some help to improve the dev cycle here?

**Comment by CPatchane** [comment]
@joeworkman I just updated the branch to resolve the conflicts, ready to merge :)

**Pull request merged**
