### PR TITLE
Do not hyphenate all td elements

### PR DESCRIPTION
**Pull request by schpet**
#143

### CODE REVIEW

**Review by DanielRuf — COMMENTED** [review]
This change is not ok as this is a breaking change.

**Comment by schpet** [comment]
@DanielRuf can you help me understand what problems this style solves?

I wonder if it would make more sense as an opt-in css class, e.g. a .break-word class for user-generated content. Having it apply to all `<td>` elements makes it difficult to override, and causes text to hyphenate instead of layout normally.

**Comment by DanielRuf** [comment]
normalize normalizes the styles between all browsers. The original normalizecss repo contains details about these rules.

**Comment by DanielRuf** [comment]
Well, you can easily override the styles in your project using the Sass setup.

Your proposed change would be a breaking change. Also please do not modify such thirdparty libraries.

**Comment by shnizmuffin** [comment]
@DanielRuf, you're incorrect. _normalize.scss is a component of foundation-emails. It shares the name of normalize.css but that's about it. (For example, [normalize doesn't touch td elements](https://github.com/necolas/normalize.css/blob/master/normalize.css).) _normalize.scss contains styles specific to certain email clients. It is **not** a third party library. Further, in a project that inlines all CSS, an override is always a worse fix than a delete, since any rules contribute to inline bloat.

That being said, @schpet, you shouldn't be putting text directly inside a `td` element. Those lines of _normalize.scss prevent the template from [getting clipped weird in certain email clients](https://www.campaignmonitor.com/css/text-fonts/word-wrap/). These clients are edge cases, but they may represent non-zero amount of your audience.

Put your text in an appropriate semantic element, like `p`. It should alleviate the problem and has the added bonus of being [more accessible](https://www.emailonacid.com/blog/article/email-development/email-accessibilty-in-2017/).

**Comment by schpet** [comment]
@shnizmuffin I have content in p tags nested inside td tags and still see this issue. both word-wrap and hyphens inherit the the values, in the same way that adding a color to a td would affect the p tags nested inside it. 

can you elaborate on the template getting clipped in some email clients? that link doesn’t seem to have info on this problem.

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

**Comment by shnizmuffin** [comment]
@schpet, the `word-wrap` rule is to address an IE6 bug, so it affects email clients that use IE6 as their renderer. Here's an [eleven year old article](http://www.positioniseverything.net/explorer/expandingboxbug.html) explaining the issue in extreme detail. 

A [bunch of email clients](https://www.campaignmonitor.com/css/text-fonts/hyphens/) don't respect the `hyphens` rule. The ones that do require the webkit prefix. I remember having a hyphenation problem way back when, so I went hunting in my code to see how I dealt with it. I found this gem inside of my `_hotfix.scss`:

```scss

// Goddamn overzealous hyphenation
td {
  -moz-hyphens: manual;
  -webkit-hyphens: manual;
  hyphens: manual;
}

```

Just remember to plop `&shy;` inside big words that _need_ to hyphenate.

**Comment by schpet** [comment]
@shnizmuffin thanks for the links and explanation! this is very helpful. i’ll have to test my fork against some ie6 based email clients.

**Comment by DanielRuf** [comment]
Closing as this might break the display in email clients.

So far we faced no issues with the code for word-break and so on.

**Pull request closed without merging**
