### PR TITLE
Large font Sizes

### PR DESCRIPTION
**Pull request by joeworkman**
Large Font Sizes

### CODE REVIEW

**Comment by jsit** [comment]
I proposed an alternate implementation in #745

**Comment by rafibomb** [comment]
There might be some confusion here - though the concept is correct.

The small-font-size variable is for the `<small>` tag not a responsive pattern.

```
/// Default font size for `<small>`.
/// @type Number
$small-font-size: 80% !default;
```

Best practices are to decrease header sizes (take up too much space already easy to read) and to increase text size of paragraphs - reference https://templates.mailchimp.com/development/responsive-email/increasing-text-size/

This already exists in Foundation for Sites http://foundation.zurb.com/sites/docs/typography-base.html#header-styles

Maybe we take that into Emails - thoughts?

**Comment by davehoran** [comment]
@rafibomb So like <small> for use in email footer text or something?

**Comment by rafibomb** [comment]
@coreyschaaf The need for responsive font sizes is being addressed here. Bumping up the p text size and lowering the header font size.

What do yo usually do?

**Comment by ghost** [comment]
@rafibomb I write my own font size structures for small vs large. The sweet spot that I use for paragraphs is16px for large and 14px for small.  Just my own formula.  In regards to headers - I use the method that foundation already supports.

**Comment by joeworkman** [comment]
I don't see why small could not be in the responsive pattern. With smaller headers the `<small>`  content may need to be made a larger percentage.

**Comment by joeworkman** [comment]
Traditionally, paragraph size should not increase on mobile. The reason that desktop should be larger is that people sit farther away from your monitor. Mobile devices are held closer to our eyes, hence small font actually is more readable.

**Comment by canterberrie** [comment]
@joeworkman This is a good idea! But if we're going to do this we should use the same format as in Foundation sites: https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L115

Also, just wanted to mention that the `<small>` tag isn't actually meant to be responsive, but used to scale text inside of headers to be smaller, more as a visual style.

**Comment by joeworkman** [comment]
I can totally agree with making the configured nicer like for sites. I can do that. 

I am not sure I understand the hesitation for making `small` responsive though. Why not give the use the option. We can make the default the same. I don't see a reason why not to give users the choice on this one. I understand that small is not used to scale header sizes. Its for adding small segments to your headers for style. My argument is still the same though...

**Pull request closed without merging**
