### PR TITLE
Fix gulp/sass Windows 64bit

### PR DESCRIPTION
**Pull request by jurri**
Error: Cannot find module 'gulp-sass'
gulp/sass doesnt work with Windows 64bit

need Version 3.1.0
https://github.com/jakearchibald/wittr/issues/20

Before submitting a pull request, make sure it's targeting the right branch:

- For fixes to Ink 1.0, use `master`.
- For fixes to Foundation for Emails 2, use `v2.0`.

Happy coding! :)

### CODE REVIEW

**Comment by AlexanderDerck** [comment]
This fixed it for me to make it work out of the box (git clone -> npm install). No need to install bower, gulp, windows-build-tools globally like other solutions suggested.

**Review by paulfevre — APPROVED** [review]
This fix the issue for me too.

**Review by DanielRuf — COMMENTED** [review]
Thanks, we will test this.

**Comment by DanielRuf** [comment]
> windows-build-tools

This is needed for packages which are not available as prebundled binaries. Then you need node-gyp and also python2 which you can install with the windows-build-tools package.

**Comment by DanielRuf** [comment]
This is superseded by https://github.com/foundation/foundation-emails/pull/971.

**Pull request closed without merging**
