### PR TITLE
Making button text color change based on background lightness

### PR DESCRIPTION
**Pull request by seanriceaz**
- Added a setting for color threshhold (default is 50).
- Added some checks for button color background to determine if the button should have the alternate color or not.
- Simplified code somewhat using "&" (and fixed a bug where non-standard sized buttons were incorrectly inheriting the standard button text color)

### CODE REVIEW

**Comment by rafibomb** [comment]
Nice PR! This a cool thing we did with callouts and buttons in Foundation for Apps. We'll be testing this today for merge!

**Comment by rafibomb** [comment]
As this is a feature, we'd like to follow the standard programing releases where features are on a major point release. Are you able to target this to the 2.2 branch?

**Comment by seanriceaz** [comment]
Sure, would you like me to make a pull request into that branch?

On Fri, May 13, 2016, 10:17 AM Rafi notifications@github.com wrote:

> Nice PR! This a cool thing we did with callouts and buttons in Foundation
> for Apps. We'll be testing this today for merge!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/zurb/foundation-emails/pull/438#issuecomment-219104700
> 
> ## 

Sean Rice
Senior UX Designer | Ethology
sean.rice@ethology.com

**Comment by seanriceaz** [comment]
I created a new pull request into the proper branch. Closing this one!

**Pull request closed without merging**
