### PR TITLE
Add style box-sizing: border-box  to _normalize.scss

### PR DESCRIPTION
**Pull request by VladimirValov**
Hello! In some email app (for example [Mail.ru - Email App](https://play.google.com/store/apps/details?id=ru.mail.mailapp&hl=en)   ) you will see broken letter for template **newsletter-2.html** 
Screenshot from 2020-09-11 12-22-18

### CODE REVIEW

**Comment by DanielRuf** [comment]
Thanks for your PR.
Can you check if this looks good in all browsers / email clients then and if there are no visual regressions?

You can test this on https://testi.at

**Comment by VladimirValov** [comment]
Hello @DanielRuf 
I have not subscription for this service. I have checked my letters in several devices, it looks good.

**Comment by DanielRuf** [comment]
> I have not subscription for this service. I have checked my letters in several devices, it looks good.

There is a free plan: https://testi.at/pricing

**Comment by VladimirValov** [comment]
I have tested on the free plan (only two Email Clients ) and real devices. I have not caught any problem/
Screenshot from 2020-09-15 09-29-00

**Review by DanielRuf — APPROVED** [review]
LGTM

**Pull request merged**
