### PR TITLE
Fix collapse class

### PR DESCRIPTION
**Pull request by rickysullivan**
Sorry for the confusion.

### CODE REVIEW

**Comment by rafibomb** [comment]
Thanks for the PR! We might have some feedback on it, but we'll test it out for now.

**Comment by rafibomb** [comment]
Unfortunately nth child selectors are not well supported so we don't use them:
https://www.campaignmonitor.com/css/b/

The collapsing works great!

Can you explain the deletion if this block? 

```
 td.large-#{$i}.first,      
 -    th.large-#{$i}.first,     
 -    td.large-#{$i}.last,      
 -    th.large-#{$i}.last {     
 -      width: -zf-grid-calc-px($i, $grid-column-count, $global-width) + ($global-gutter * 1.5);
```

It's also helpful to have each change in a separate PR so when testing it's easy to isolate issues.

**Comment by rickysullivan** [comment]
Ahh. Your setting the width of the first and last column. But because it's collapsed, the width will be no different to any other column in the row now that it will be collapsed. Sorry for the terrible git skills.

**Comment by rickysullivan** [comment]
Will submit a new PR.

**Pull request closed without merging**
