### PR TITLE
Fix expanded button width

### PR DESCRIPTION
**Pull request by Stadly**
Fix issue introduced by https://github.com/foundation/foundation-emails/pull/791.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @Stadly,

we use the `expanded` class as you can see at https://foundation.zurb.com/emails/docs/button.html#expanded

Can you provide an example where the current code does not work and is fixed by your PR?

**Comment by Stadly** [comment]
Both `expand` and `expanded` should be supported: https://github.com/foundation/foundation-emails/blob/220e44ffa6da5f8d0151ede057a55313f88dfcfe/scss/components/_button.scss#L146

**Comment by DanielRuf** [comment]
> Both `expand` and `expanded` should be supported:

I miss some context where you have found `expand` as we do not mention this in the Foundation Emails documentation.

**Comment by Stadly** [comment]
The context is the source code i linked to: https://github.com/foundation/foundation-emails/blob/220e44ffa6da5f8d0151ede057a55313f88dfcfe/scss/components/_button.scss#L146

`expand` is a synonym for `expanded`, even if it is not mentioned in the documentation.

It is used in several templates: https://github.com/foundation/foundation-emails/blob/220e44ffa6da5f8d0151ede057a55313f88dfcfe/templates/marketing.html#L66

**Comment by DanielRuf** [comment]
Thank you, we will check that if we have missed that or deprecated it.

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
